

#### APi_1 scenario_1:

GET http://localhost:3000/todos/?status=TO%20DO

#### scenario_2:


GET http://localhost:3000/todos/?priority=HIGH


## scenario_3:

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###scenario_4:

GET http://localhost:3000/todos/?search_q=play

###s APi_2 :

GET http://localhost:3000/todos/1/


#### APi_3 :


POST http://localhost:3000/todos/ 
Content-Type:application/json


{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}


### APi_4:

PUT http://localhost:3000/todos/1/
Content-Type:application/json

{
  "status":"DONE"
}

### scenario_2:


PUT http://localhost:3000/todos/2
Content-Type:application/json 

{
  "priority:"HIGH"
}

### scenario_3:

PUT http://localhost:3000/todos/3
Content-Type:application/json 

{ 
  "todo": "Some task" 
}

#### APi_5 :

DELETE http://localhost:3000/todos/1/


